set foreign_key_checks = 0;
drop table if exists items;

set foreign_key_checks = 1;


create table items
(
	category varchar(20),
    type varchar(20),
    name varchar(50),
    size varchar(20),
	price dec(5,2),
    primary key(name, size)
);

insert into items(category, type, name, size, price)
values
(	'Lunch'	,		'Beverage'	,	'Coca-Cola Classic'	,			'Small'	,		1.49	)	,
(	'Lunch'	,		'Beverage'	,	'Coca-Cola Classic'	,			'Medium'	,	2.29	)	,
(	'Lunch'	,		'Beverage'	,	'Coca-Cola Classic'	,			'Large'	,		2.59	)	,
(	'Lunch'	,		'Beverage'	,	'Diet Coke'	,					'Small'	,		1.49	)	,
(	'Lunch'	,		'Beverage'	,	'Diet Coke'	,					'Medium'	,	2.29	)	,
(	'Lunch'	,		'Beverage'	,	'Diet Coke'	,					'Large'	,		2.59	)	,
(	'Lunch'	,		'Beverage'	,	'Dr Pepper'	,					'Small'	,		1.49	)	,
(	'Lunch'	,		'Beverage'	,	'Dr Pepper'	,					'Medium'	,	2.29	)	,
(	'Lunch'	,		'Beverage'	,	'Dr Pepper'	,					'Large'	,		2.59	)	,
(	'Lunch'	,		'Beverage'	,	'Diet Dr Pepper'	,			'Small'	,		1.49	)	,
(	'Lunch'	,		'Beverage'	,	'Diet Dr Pepper'	,			'Medium'	,	2.29	)	,
(	'Lunch'	,		'Beverage'	,	'Diet Dr Pepper'	,			'Large'	,		2.59	)	,
(	'Lunch'	,		'Beverage'	,	'Sprite'	,					'Small'	,		1.49	)	,
(	'Lunch'	,		'Beverage'	,	'Sprite'	,					'Medium'	,	2.29	)	,
(	'Lunch'	,		'Beverage'	,	'Sprite'	,					'Large'	,		2.59	)	,
(	'Lunch'	,		'Beverage'	,	'Minute Maid Orange Juice'	,	'Small'	,		1.49	)	,
(	'Lunch'	,		'Beverage'	,	'Minute Maid Orange Juice'	,	'Medium'	,	2.29	)	,
(	'Lunch'	,		'Beverage'	,	'Minute Maid Orange Juice'	,	'Large'	,		2.59	)	,
(	'Lunch'	,		'Side'	,		'Fries'	,						'small'	,		2.49	)	,
(	'Lunch'	,		'Side'	,		'Fries'	,						'medium'	,	3.09	)	,
(	'Lunch'	,		'Side'	,		'Fries'	,						'large'	,		3.49	)	,
(	'Lunch'	,		'Side'	,		'Curly Fries'	,				'regular'	,	3.49	)	,
(	'Lunch'	,		'Side'	,		'Camembert Donuts'	,			'small'	,		3.89	)	,
(	'Lunch'	,		'Side'	,		'Camembert Donuts'	,			'medium'	,	4.89	)	,
(	'Lunch'	,		'Main'	,		'Big Mac'	,					'regular'	,	5.29	)	,
(	'Lunch'	,		'Main'	,		'Big Tasty Bacon'	,			'regular'	,	7.39	)	,
(	'Lunch'	,		'Main'	,		'Cheeseburger'	,				'regular'	,	1.49	)	,
(	'Lunch'	,		'Main'	,		'Chickenburger'	,				'regular'	,	1.49	)	,
(	'Lunch'	,		'Main'	,		'Chicken Box'	,				'regular'	,	9.99	)	,
(	'Lunch'	,		'Main'	,		'Chicken McNuggets'	,			'small'	,		4.89	)	,
(	'Lunch'	,		'Main'	,		'Chicken McNuggets'	,			'medium'	,	5.99	)	,
(	'Lunch'	,		'Main'	,		'Chicken McNuggets'	,			'large'	,		9.99	)	,
(	'Lunch'	,		'Main'	,		'Chicken Wings'	,				'regular'	,	4.19	)	,
(	'Lunch'	,		'Main'	,		'Double-Cheeseburger'	,		'regular'	,	2.49	)	,
(	'Lunch'	,		'Main'	,		'Filet-o-Fish'	,				'regular'	,	4.89	)	,
(	'Lunch'	,		'Main'	,		'Hamburger'	,					'regular'	,	1.29	)	,
(	'Lunch'	,		'Main'	,		'Hamburger Royal'	,			'regular'	,	5.29	)	,
(	'Lunch'	,		'Main'	,		'McRib'	,						'regular'	,	5.29	)	,
(	'Lunch'	,		'Main'	,		'Veggieburger TS'	,			'regular'	,	2.49	)	,
(	'Lunch'	,		'Main'	,		'McChicken Classic Deluxe'	,	'regular'	,	5.49	)	,
(	'Lunch'	,		'Dessert'	,	'Schoko Muffin'	,				'regular'	,	2.89	)	,
(	'Lunch'	,		'Dessert'	,	'Candy Donut'	,				'regular'	,	1.79	)	,
(	'Lunch'	,		'Dessert'	,	'Schoko Donut'	,				'regular'	,	1.79	)	,
(	'Lunch'	,		'Dessert'	,	'Vanille Donut'	,				'regular'	,	1.79	)	,
(	'Lunch'	,		'Dessert'	,	'Cookie Tripple Choc'	,		'regular'	,	1.29	)	,
(	'Lunch'	,		'Dessert'	,	'Cookie Choc'	,				'regular'	,	1.29	)	,
(	'Lunch'	,		'Dessert'	,	'McFlurry'	,					'regular'	,	3.69	)	,
(	'Breakfast'	,	'Main'	,		'Egg McMuffin'	,				'regular'	,	2.79	)	,
(	'Breakfast'	,	'Main'	,		'Egg White Delight'	,			'regular'	,	2.79	)	,
(	'Breakfast'	,	'Main'	,		'Sausage McMuffin'	,			'regular'	,	2.59	)	,
(	'Breakfast'	,	'Main'	,		'Steak Egg McMuffin'	,		'regular'	,	3.99	)	,
(	'Breakfast'	,	'Main'	,		'Bacon Egg Cheese Biscuit',		'regular'	,	3.29	)	,
(	'Breakfast'	,	'Main'	,		'Bacon Egg Cheese Biscuit',		'large'	,		3.99	)	,
(	'Breakfast'	,	'Main'	,		'Sausage Biscuit'	,			'regular'	,	2.59	)	,
(	'Breakfast'	,	'Main'	,		'Sausage Biscuit'	,			'large'	,		2.99	)	,
(	'Breakfast'	,	'Main'	,		'Southern Style Chicken Biscuit','regular'	,	2.79	)	,
(	'Breakfast'	,	'Main'	,		'Southern Style Chicken Biscuit','large'	,	3.29	)	,
(	'Breakfast'	,	'Beverage'	,	'Iced Tea'	,					'small'	,		1.00	)	,
(	'Breakfast'	,	'Beverage'	,	'Iced Tea'	,					'medium'	,	1.29	)	,
(	'Breakfast'	,	'Beverage'	,	'Iced Tea'	,					'large'	,		1.49	)	,
(	'Breakfast'	,	'Beverage'	,	'Sweet Tea'	,					'small'	,		1.49	)	,
(	'Breakfast'	,	'Beverage'	,	'Sweet Tea'	,					'medium'	,	2.29	)	,
(	'Breakfast'	,	'Beverage'	,	'Sweet Tea'	,					'large'	,		2.59	)	,
(	'Breakfast'	,	'Beverage'	,	'Coffee'	,					'small'	,		1.00	)	,
(	'Breakfast'	,	'Beverage'	,	'Coffee'	,					'medium'	,	1.29	)	,
(	'Breakfast'	,	'Beverage'	,	'Coffee'	,					'large'	,		1.49	)	,
(	'Breakfast'	,	'Beverage'	,	'Latte'	,						'small'	,		1.49	)	,
(	'Breakfast'	,	'Beverage'	,	'Latte'	,						'medium'	,	2.29	)	,
(	'Breakfast'	,	'Beverage'	,	'Latte'	,						'large'	,		2.59	)	,
(	'Breakfast'	,	'Beverage'	,	'Caramel Latte'	,				'small'	,		2.39	)	,
(	'Breakfast'	,	'Beverage'	,	'Caramel Latte'	,				'medium'	,	2.89	)	,
(	'Breakfast'	,	'Beverage'	,	'Caramel Latte'	,				'large'	,		3.39	)	,
(	'Breakfast'	,	'Beverage'	,	'Hazelnut Latte'	,			'small'	,		2.39	)	,
(	'Breakfast'	,	'Beverage'	,	'Hazelnut Latte'	,			'medium'	,	2.89	)	,
(	'Breakfast'	,	'Beverage'	,	'Hazelnut Latte'	,			'large'	,		3.39	)	,
(	'Breakfast'	,	'Beverage'	,	'French Vanilla Latte'	,		'small'	,		2.39	)	,
(	'Breakfast'	,	'Beverage'	,	'French Vanilla Latte'	,		'medium'	,	2.89	)	,
(	'Breakfast'	,	'Beverage'	,	'French Vanilla Latte'	,		'large'	,		3.39	)	;


select * from items;
