DROP TRIGGER IF EXISTS setOrderInfoDate;
DROP TRIGGER IF EXISTS setOrderContentsDate;

DELIMITER |
CREATE TRIGGER setOrderInfoDate BEFORE INSERT ON orderInfo
	FOR EACH ROW
		SET NEW.orderDate = CURRENT_TIMESTAMP();
|
DELIMITER ;


DELIMITER |
CREATE TRIGGER setOrderContentsDate BEFORE INSERT ON orderContents
	FOR EACH ROW
		SET NEW.orderDate = CURRENT_TIMESTAMP();
|
DELIMITER ;